version: '3'
services:
  postgresql:
    container_name: postgresql
    image: postgres:12
    environment:
      - POSTGRES_USER=<no value>
      - POSTGRES_PASSWORD=<no value>
      - POSTGRES_DB=<no value>

  xyauth:
    container_name: xyauth
    image: xyauth:latest
    ports:
      - "127.0.0.1:8443:8443"
    environment:
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=<no value>
      - POSTGRES_USER=<no value>
      - POSTGRES_PASSWORD=<no value>
      - POSTGRES_DB=<no value>
    depends_on:
      - postgresql
